# Cấu hình Gradle dùng chung toàn dự án.
# Người dùng IDE, ví dụ Android Studio:
# Cấu hình Gradle đặt qua IDE sẽ ghi đè
# mọi cấu hình được khai báo trong file này.
# Xem thêm cách cấu hình môi trường build tại
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Chỉ định tham số JVM dùng cho tiến trình daemon.
# Cấu hình này hữu ích khi cần tinh chỉnh bộ nhớ.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# Khi bật, Gradle chạy ở chế độ song song đang thử nghiệm.
# Chỉ nên dùng tùy chọn này với project đã tách phụ thuộc giữa module. Xem thêm tại
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
# Tương thích KSP với Kotlin tích hợp trong AGP 9.
android.disallowKotlinSourceSets=false
